In [1]:
import pandas as pd
import csv

import numpy as np
import matplotlib.pyplot as plt


import tensorflow as tf
from tensorflow import keras
from tensorflow.keras import layers

In [19]:
# notebook para treinar a nn e conferir com a pré-treinada do phylodeep

def load_data_wrapper():
    # Função semelhante ao load_data, porém, o y do training_data
    # agora é um vetor unitário, representando a classificação correta para x.
    # Para o validation_data e test_data, o y é semelhante a função load_data
    # Abrindo o npz_load com as árvores
    data = np.load('C:\\Users\\JPC\Documents\\MESTRADO\\Projeto\\gillespie-2\\deep_learning_dataset_refatorado.npz',allow_pickle=True)
    

    # Abrindo as info de classificação
    with open('C:\\Users\\JPC\\Documents\\MESTRADO\\Projeto\\gillespie-2\\input_classificacao.txt') as f:
        reader = csv.reader(f, delimiter="\t")
        input_class = list(reader)

    # Removendo o header das info de classificação
    input_class.pop(0)

    # Retornando a segunda coluna (coluna referente ao R_nought)
    # e em segunda transformando a lista em um np.array
    R_nought = [sublist[5] for sublist in input_class]
    R_nought = np.array(R_nought)

    transmission_rate = [sublist[1] for sublist in input_class]
    transmission_rate = np.array(transmission_rate)

    infectious_time = [sublist[6] for sublist in input_class]
    infectious_time = np.array(infectious_time)

    vectorized = []
    for n in range(0, len(transmission_rate)):
        vectorized.append([float(transmission_rate[n]), float(infectious_time[n])])

    #R_nought_vector = []
    ##np.array([1, 0]) if i == 1 else np.array([0, 1]) for i in R_nought
    #for i in R_nought:
    #    if i == '1':
    #        R_nought_vector.append([float(1)])
    #        #R_nought_vector.append([1, 0])
    #    else:
    #        #R_nought_vector.append([5, 1])
    #        R_nought_vector.append([float(5)])

    #R_nought_vector = np.array(R_nought_vector)



    training_data = list(zip(data['tree_data'][:20], R_nought[:20], transmission_rate[:20], infectious_time[:20], vectorized[:20]))
    

    #validation_data = list(zip(data['tree_data'][8000:9000], R_nought_vector[8000:9000]))

    test_data = list(zip(data['tree_data'][0:20], R_nought[0:20], transmission_rate[0:20], infectious_time[0:20], vectorized[0:20]))
    
    return training_data, test_data



# Criar o loop do mini-batch e confere os erros
# Tentar pelo tensorflow

In [3]:
# O training data tem 90.000 obsevações, sendo cada observação a árvore de tamanho 402, o R_0, transmission_rate, infectious_time, a lista deles

In [4]:
'''
training_data, test_data = load_data_wrapper()
#x_train = [sublist[0].reshape(-1,1) for sublist in training_data]
x_train = [sublist[0] for sublist in training_data]
y_train = [float(sublist[1]) for sublist in training_data]
testar_formato =  [float(sublist[3]) for sublist in training_data]

x_train = np.asarray(x_train)
y_train = np.asarray(y_train)
testar_formato = np.asarray(testar_formato)
#--------------------
x_test = [sublist[0] for sublist in test_data]

y_test = [float(sublist[1]) for sublist in test_data]

x_test = np.asarray(x_test)
y_test = np.asarray(y_test)
'''

'\ntraining_data, test_data = load_data_wrapper()\n#x_train = [sublist[0].reshape(-1,1) for sublist in training_data]\nx_train = [sublist[0] for sublist in training_data]\ny_train = [float(sublist[1]) for sublist in training_data]\ntestar_formato =  [float(sublist[3]) for sublist in training_data]\n\nx_train = np.asarray(x_train)\ny_train = np.asarray(y_train)\ntestar_formato = np.asarray(testar_formato)\n#--------------------\nx_test = [sublist[0] for sublist in test_data]\n\ny_test = [float(sublist[1]) for sublist in test_data]\n\nx_test = np.asarray(x_test)\ny_test = np.asarray(y_test)\n'

In [20]:
training_data, test_data = load_data_wrapper()

In [21]:
x_train = [sublist[0] for sublist in training_data]
y_train = [float(sublist[3]) for sublist in training_data]
testar_formato =  [float(sublist[3]) for sublist in training_data]

x_train = np.asarray(x_train)
y_train = np.asarray(y_train)

#x_train_normalized = [(tree - min(tree))/(max(tree)-min(tree)) for tree in x_train]
#x_train_normalized = (x_train - min(x_train))/(max(x_train)-min(x_train))


#x_train_normalized = np.asarray(x_train_normalized)

#-------------------------------------------------------------------

x_test = [sublist[0] for sublist in test_data]
y_test = [float(sublist[3]) for sublist in test_data]

x_test = np.asarray(x_test)
y_test = np.asarray(y_test)

In [ ]:
x_train[1]

array([0.        , 6.92476669, 5.34010782, 6.6544203 , 5.08290405,
       6.32028308, 6.13572829, 6.46428102, 5.64283906, 5.4728137 ,
       4.57060468, 6.3571345 , 4.47681855, 6.60884993, 7.01004757,
       6.36521048, 5.60690274, 5.87927215, 5.69064077, 5.79359047,
       5.5943216 , 6.06962854, 6.13451864, 6.68349907, 5.31348943,
       4.68584203, 4.31004568, 6.99244987, 5.97960205, 7.42594184,
       5.28634494, 4.91540775, 6.59503285, 3.95027027, 7.77653459,
       6.87264966, 4.40753557, 4.30439705, 7.97202095, 6.8218925 ,
       6.38424272, 6.53368384, 4.44940322, 4.45333075, 4.73530826,
       4.80950985, 3.66629335, 6.57539827, 5.76462874, 5.5944562 ,
       5.33618587, 6.52400732, 5.9526053 , 4.86609328, 6.43062136,
       6.32285121, 6.04954174, 5.41527917, 5.27670072, 5.80710761,
       5.6429649 , 6.11404707, 4.63295215, 3.84155885, 6.54804585,
       7.51092347, 6.55765704, 7.43004764, 6.10152576, 6.7818029 ,
       6.40068866, 3.27582852, 2.26306667, 6.90030419, 6.37543692,
       6.36781558, 5.61907274, 4.35142105, 5.19083307, 2.15664362,
       5.85299889, 4.83628886, 5.20960477, 4.48443831, 6.22426024,
       4.89698011, 5.60180465, 5.54962384, 5.38416042, 5.10038066,
       4.39256955, 7.1323841 , 7.06336546, 6.1253075 , 5.60936786,
       7.67876162, 5.05584728, 4.42053147, 2.63236524, 6.13783454,
       4.30514636, 2.05486901, 6.71950648, 6.35115453, 5.67030835,
       6.38785224, 6.54373869, 4.47757156, 6.48309863, 6.01243441,
       6.99310639, 7.89843738, 6.85695326, 6.6298687 , 6.32204723,
       6.28540087, 5.44008747, 6.34982511, 6.06234365, 7.27126123,
       5.60159485, 5.28059272, 7.25493789, 5.63910662, 4.75091145,
       6.00195016, 3.29435336, 7.94907369, 6.4156359 , 6.35313066,
       6.25017547, 6.94074121, 5.61929572, 5.89648221, 3.86431231,
       4.97133968, 4.09408596, 7.82784275, 6.75497831, 6.46584842,
       5.49914484, 3.82785563, 7.64188623, 7.53766071, 6.47426926,
       5.80957975, 4.10553066, 7.27464159, 4.93297148, 5.77428493,
       7.57005127, 5.97882805, 6.27345418, 6.02872953, 4.45004539,
       6.53206502, 5.74570625, 4.36758459, 7.39214586, 5.33361867,
       6.50800439, 2.83030344, 1.84442859, 6.15376714, 4.94962961,
       0.        , 7.30407094, 5.92391039, 7.00991793, 4.75003169,
       5.64358329, 5.0200591 , 6.46752935, 6.42181543, 5.97398368,
       6.19147195, 5.19799709, 4.80063217, 4.13909884, 5.55228487,
       3.78954832, 5.52374604, 7.03268026, 6.85420169, 5.22744132,
       6.000161  , 4.68242668, 3.3982596 , 5.85115317, 5.55612392,
       6.05446391, 6.03343446, 7.66408944, 6.74054005, 5.91611072,
       2.38484799, 0.        , 0.        , 0.        , 1.        ,
       0.        , 8.57672171, 1.49025301, 3.18824184, 1.60520407,
       3.47176032, 1.58429288, 2.30266301, 1.92452416, 1.65895738,
       3.02964704, 3.80106684, 1.60186179, 3.92802411, 0.86062992,
       0.3747551 , 1.93056305, 2.3218643 , 1.45030022, 1.14046598,
       0.59570556, 2.71390059, 2.19064969, 2.08889019, 1.26687574,
       1.36691882, 2.59609084, 3.77641601, 0.97896501, 1.84750764,
       0.10329398, 1.83185463, 2.85051687, 0.5279876 , 4.58894887,
       0.58605618, 0.78979411, 0.4060776 , 3.95585917, 0.26665061,
       0.97830395, 1.73466236, 0.45967499, 3.42744443, 2.79578923,
       2.25783043, 1.32204717, 4.86417717, 1.81398151, 2.42993467,
       0.78667888, 3.05939688, 1.46578587, 0.69721824, 3.61452132,
       1.81762944, 1.32308324, 2.31251652, 2.88794579, 2.90885904,
       1.19714865, 2.43952343, 1.23289509, 1.53325605, 4.67333378,
       1.93229469, 0.03887537, 1.0375084 , 0.1254304 , 2.31122935,
       1.60439278, 0.38177469, 0.08152717, 6.11400585, 0.63206853,
       1.67012149, 0.74296629, 0.1826013 , 3.18509147, 2.29273246,
       6.38027478, 0.01590077, 2.99111217, 2.60400493, 3.79202437,
       0.7252262 , 3.28170905, 0.99029988, 1.07757965, 2.32721985,
       2.29803767, 4.0997328 , 0.84381699, 0.66356213, 0.85444846,
       2.21383451, 0.02229717, 1.18527006, 0.50174859, 5.90242761,
       1.93177053, 4.13793304, 6.4733827 , 1.31000136, 1.40732092,
       2.38278185, 0.72477975, 0.2188264 , 4.04869174, 2.03171197,
       2.45153102, 1.15727457, 0.08607699, 1.25377725, 1.32973777,
       2.01211683, 1.27140875, 2.95425453, 1.75960061, 2.10601283,
       0.50860429, 1.75892369, 3.05079046, 1.04503098, 0.66445474,
       1.28578034, 0.01139842, 5.22885529, 0.464239  , 1.97759312,
       1.75035804, 1.52764057, 0.0527407 , 2.53418853, 0.98806477,
       4.56694367, 3.22904233, 4.24073894, 0.4173987 , 0.85047578,
       1.85806112, 0.71183101, 4.67667008, 0.80026717, 0.36644457,
       1.50583906, 2.67728808, 4.27240864, 0.41201217, 3.34597231,
       2.27830697, 0.31469353, 1.92386545, 1.49756034, 0.48732309,
       3.07223099, 0.788586  , 1.22280846, 3.95969535, 0.58803351,
       2.35579786, 0.03920413, 0.17234864, 6.42333932, 1.1984627 ,
       2.92545085, 8.54421702, 0.22940407, 2.14077027, 0.80898353,
       3.68423912, 2.19631217, 3.17894888, 1.16516339, 1.06953626,
       1.0706693 , 0.5273978 , 1.7959295 , 1.07631892, 3.97851793,
       2.5456515 , 4.54644751, 2.38242962, 0.82910298, 0.44576672,
       2.56781185, 0.02572508, 0.88442655, 4.86047984, 1.43423668,
       2.66168755, 1.66780369, 1.96389563, 0.26621147, 0.4750235 ,
       1.55773753, 2.09818209, 0.        , 0.        , 0.        ,
       1.        , 0.        ])

In [12]:
modelo_derivado = tf.keras.models.Sequential([
    layers.Input(x_train[0].shape),
    layers.Reshape((201, 2)),
    layers.Conv1D(filters = 50, kernel_size = 3, activation='relu'),
    layers.Conv1D(filters = 50, kernel_size = 10, activation='relu'),
    layers.MaxPooling1D(pool_size=10),
    layers.Conv1D(filters = 80, kernel_size = 10, activation='relu'),
    layers.GlobalAveragePooling1D(),
    layers.Dense(64, activation='elu'),
    layers.Dense(32, activation='elu'),
    layers.Dense(16, activation='elu'),
    layers.Dense(8, activation='elu'),
    layers.Dense(2, activation='elu'),
    layers.Dense(1, activation='linear')
    ])

In [13]:
modelo_derivado.compile(optimizer='adam', loss='MeanAbsolutePercentageError', metrics=['accuracy'])

modelo_derivado.summary()

Model: "sequential"

┏━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━┓
┃ Layer (type)                    ┃ Output Shape           ┃       Param # ┃
┡━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━┩
│ reshape (Reshape)               │ (None, 201, 2)         │             0 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ conv1d (Conv1D)                 │ (None, 199, 50)        │           350 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ conv1d_1 (Conv1D)               │ (None, 190, 50)        │        25,050 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ max_pooling1d (MaxPooling1D)    │ (None, 19, 50)         │             0 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ conv1d_2 (Conv1D)               │ (None, 10, 80)         │        40,080 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ global_average_pooling1d        │ (None, 80)             │             0 │
│ (GlobalAveragePooling1D)        │                        │               │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ dense (Dense)                   │ (None, 64)             │         5,184 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ dense_1 (Dense)                 │ (None, 32)             │         2,080 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ dense_2 (Dense)                 │ (None, 16)             │           528 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ dense_3 (Dense)                 │ (None, 8)              │           136 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ dense_4 (Dense)                 │ (None, 2)              │            18 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ dense_5 (Dense)                 │ (None, 1)              │             3 │
└─────────────────────────────────┴────────────────────────┴───────────────┘

 Total params: 73,429 (286.83 KB)

 Trainable params: 73,429 (286.83 KB)

 Non-trainable params: 0 (0.00 B)

In [14]:
history = modelo_derivado.fit(x_train, y_train, epochs=10, batch_size=32, validation_split=0.2)

Epoch 1/10
1/1 ━━━━━━━━━━━━━━━━━━━━ 2s 2s/step - accuracy: 0.0000e+00 - loss: 99.5457 - val_accuracy: 0.0000e+00 - val_loss: 97.8680
Epoch 2/10
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 34ms/step - accuracy: 0.0000e+00 - loss: 97.9610 - val_accuracy: 0.0000e+00 - val_loss: 96.5255
Epoch 3/10
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 51ms/step - accuracy: 0.0000e+00 - loss: 96.6531 - val_accuracy: 0.0000e+00 - val_loss: 94.9866
Epoch 4/10
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 49ms/step - accuracy: 0.0000e+00 - loss: 95.1292 - val_accuracy: 0.0000e+00 - val_loss: 93.1105
Epoch 5/10
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 49ms/step - accuracy: 0.0000e+00 - loss: 93.2060 - val_accuracy: 0.0000e+00 - val_loss: 90.7641
Epoch 6/10
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 50ms/step - accuracy: 0.0000e+00 - loss: 90.7205 - val_accuracy: 0.0000e+00 - val_loss: 87.7771
Epoch 7/10
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 49ms/step - accuracy: 0.0000e+00 - loss: 87.4866 - val_accuracy: 0.0000e+00 - val_loss: 83.9599
Epoch 8/10
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 50ms/step - accuracy: 0.0000e+00 - loss: 83.2939 - val_accuracy: 0.0000e+00 - val_loss: 79.0816
Epoch 9/10
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 34ms/step - accuracy: 0.0000e+00 - loss: 77.8861 - val_accuracy: 0.0000e+00 - val_loss: 72.9010
Epoch 10/10
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 37ms/step - accuracy: 0.0000e+00 - loss: 70.9933 - val_accuracy: 0.0000e+00 - val_loss: 65.1284

In [11]:
# Como usar o evaluate?
# modelo_derivado.evaluate(x_test, y_test)

In [12]:
y_predict = modelo_derivado.predict(x_train[:20])
y_predict

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 94ms/step

array([[1.2835516],
       [1.2026781],
       [1.279068 ],
       [1.2813556],
       [1.2836611],
       [1.2840234],
       [1.2840788],
       [1.2838132],
       [1.2840846],
       [1.2837622],
       [1.2836986],
       [1.282646 ],
       [1.2805463],
       [1.2805463],
       [1.2838736],
       [1.2840638],
       [1.2840638],
       [1.2840165],
       [1.2802601],
       [1.2802601]], dtype=float32)

In [13]:
y_predict = modelo_derivado.predict(x_test[9980:])
y_predict

c:\Users\JPC\anaconda3\envs\phylodeepenv\lib\contextlib.py:153: UserWarning: Your input ran out of data; interrupting training. Make sure that your dataset or generator can generate at least `steps_per_epoch * epochs` batches. You may need to use the `.repeat()` function when building your dataset.
  self.gen.throw(typ, value, traceback)

ValueError: math domain error

In [ ]:
y_test[9980:]

array([0.07199942, 0.39200314, 0.3869969 , 0.07099752, 0.36101083,
       0.46403712, 0.48899756, 0.34094783, 0.36603221, 0.450045  ,
       0.31897927, 0.07900142, 0.1499925 , 0.12899897, 0.32404407,
       0.09500285, 0.04800077, 0.13500743, 0.05699954, 0.4950495 ])

In [ ]:
y_predict_discreto = [5 if n>3 else 1 for n in y_predict]
y_predict_discreto = np.asarray(y_predict_discreto).reshape(-1,1)
y_predict_discreto

array([[5],
       [1],
       [1],
       ...,
       [5],
       [1],
       [5]], shape=(10000, 1))

In [ ]:

accuracy = np.where(y_test==y_predict_discreto, True, False)
print(f'A taxa de acerto foi de {np.sum(accuracy)/10000}.')

A taxa de acerto foi de 0.9847.

In [ ]:
resultados = pd.DataFrame(y_test, columns=['y_test'])
resultados['y_predict_discreto'] = y_predict_discreto
resultados['acerto'] = accuracy
resultados['y_predict'] = y_predict
resultados.head()

   y_test  y_predict_discreto  acerto  y_predict
0     5.0                   5    True   4.993727
1     1.0                   1    True   1.002230
2     1.0                   1    True   1.002302
3     5.0                   5    True   4.990980
4     1.0                   1    True   1.002239

In [ ]:
resultados.query('y_predict > 1.01 and y_predict < 4.99 and acerto == False').head()

      y_test  y_predict_discreto  acerto  y_predict
297      1.0                   5   False   4.989597
382      1.0                   5   False   4.989485
903      1.0                   5   False   4.989435
1335     1.0                   5   False   4.989088
1372     1.0                   5   False   4.988916

In [ ]:
resultados[~accuracy]

      y_test  y_predict_discreto  acerto  y_predict
65       1.0                   5   False   4.992354
137      1.0                   5   False   4.990974
182      1.0                   5   False   4.990756
239      1.0                   5   False   4.990712
297      1.0                   5   False   4.989597
...      ...                 ...     ...        ...
9788     1.0                   5   False   4.991968
9874     1.0                   5   False   4.988726
9905     1.0                   5   False   4.992577
9969     1.0                   5   False   4.990398
9977     1.0                   5   False   4.992639

[153 rows x 4 columns]


---

In [15]:
modelo_original = tf.keras.models.load_model('C:\\Users\\JPC\\Documents\\MESTRADO\\Projeto\\gillespie-2\\BD_SMALL_CNN.h5')

modelo_original.summary()

c:\Users\JPC\anaconda3\envs\phylodeepenv\lib\site-packages\keras\src\layers\reshaping\reshape.py:39: UserWarning: Do not pass an `input_shape`/`input_dim` argument to a layer. When using Sequential models, prefer using an `Input(shape)` object as the first layer in the model instead.
  super().__init__(**kwargs)
c:\Users\JPC\anaconda3\envs\phylodeepenv\lib\site-packages\keras\src\layers\convolutional\base_conv.py:107: UserWarning: Do not pass an `input_shape`/`input_dim` argument to a layer. When using Sequential models, prefer using an `Input(shape)` object as the first layer in the model instead.
  super().__init__(activity_regularizer=activity_regularizer, **kwargs)
WARNING:absl:No training configuration found in the save file, so the model was *not* compiled. Compile it manually.

Model: "sequential_1"

┏━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━┓
┃ Layer (type)                    ┃ Output Shape           ┃       Param # ┃
┡━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━┩
│ reshape_1 (Reshape)             │ (None, 201, 2)         │             0 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ conv1d_1 (Conv1D)               │ (None, 199, 50)        │           350 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ conv1d_2 (Conv1D)               │ (None, 190, 50)        │        25,050 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ max_pooling1d_1 (MaxPooling1D)  │ (None, 19, 50)         │             0 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ conv1d_3 (Conv1D)               │ (None, 10, 80)         │        40,080 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ global_average_pooling1d_1      │ (None, 80)             │             0 │
│ (GlobalAveragePooling1D)        │                        │               │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ dense_1 (Dense)                 │ (None, 64)             │         5,184 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ dense_2 (Dense)                 │ (None, 32)             │         2,080 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ dense_3 (Dense)                 │ (None, 16)             │           528 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ dense_4 (Dense)                 │ (None, 8)              │           136 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ dense_5 (Dense)                 │ (None, 2)              │            18 │
└─────────────────────────────────┴────────────────────────┴───────────────┘

 Total params: 73,426 (286.82 KB)

 Trainable params: 73,426 (286.82 KB)

 Non-trainable params: 0 (0.00 B)

In [16]:
modelo_original.compile(optimizer='adam', loss='MeanAbsoluteError', metrics=['accuracy'])

In [22]:
x_test.shape

(20, 402)

In [23]:
predica = modelo_original.predict(x_test[:20])
print(predica)

# pegar a do vinicius q estima R_0 e 1/gamma, 
# treinar só pro infectious
# registrar oq ja fizemos
# testar as 100 arvores geradas
# testar com o remove_rate (inversa do infectiuos time)
#-------------------------------------------------------

#~Exportar a arvore e testar no R
#!Gerar as arvores com treegeneratortest no dropbox
#!Gerar com betafixado e varia só o gamma 
#!estudar o gillepsie

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 88ms/step
[[1.237159  2.351757 ]
 [4.99232   5.3709536]
 [1.4205328 2.496621 ]
 [1.1583049 2.2771776]
 [1.0829263 2.15387  ]
 [4.9842286 4.985589 ]
 [1.066731  2.1383193]
 [1.1093969 2.2056127]
 [4.9486804 4.96428  ]
 [4.60709   5.3198123]
 [1.1092093 2.1692243]
 [4.7922635 5.5119486]
 [4.6945724 5.222474 ]
 [1.2163239 2.321057 ]
 [1.2598184 2.4067974]
 [4.94824   5.420623 ]
 [1.0665967 2.1609669]
 [4.5275106 5.4045234]
 [1.1320645 2.225988 ]
 [4.7732606 5.521165 ]]

In [ ]:
import inspect

import phy

print(inspect.getsource(phy.remove_certain_leaves))